<a href="https://colab.research.google.com/github/Lavan1999/Datasets-1--TIps/blob/main/Tips.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Library

In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np
from scipy import stats
import plotly.graph_objects as go
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns


# DataFrame

In [ ]:
df = sns.load_dataset('tips')
df.to_csv('tips.csv', index=False)

In [ ]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# Dataframe observation
Supervised [Classification / Regression] (or) Unsupervised [Clustering / Association]

Continuous column

Category column

In [ ]:
#Unsupervised

#Continuous - total_bill, tip
#Category - sex,	smoker,	day,	time,	size

#corr

# Statistical analysis
Continuous - Central Limit Theorem, 1-Tailed Test (one-sample t-test)

Continuous vs. Continuous - Correlation, 2-Tailed Test (two-sample t-test)

Continuous vs. Categorical - ANOVA (Analysis of Variance)

Categorical vs. Categorical - Chi-Square Test

# Correlation

In [ ]:
df.corr()

<ipython-input-8-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

# Central Limit Theorem

In [ ]:
#total_bill
population=df.total_bill.values
population

array([16.99, 10.34, 21.01, 23.68, 24.59, 25.29,  8.77, 26.88, 15.04,
       14.78, 10.27, 35.26, 15.42, 18.43, 14.83, 21.58, 10.33, 16.29,
       16.97, 20.65, 17.92, 20.29, 15.77, 39.42, 19.82, 17.81, 13.37,
       12.69, 21.7 , 19.65,  9.55, 18.35, 15.06, 20.69, 17.78, 24.06,
       16.31, 16.93, 18.69, 31.27, 16.04, 17.46, 13.94,  9.68, 30.4 ,
       18.29, 22.23, 32.4 , 28.55, 18.04, 12.54, 10.29, 34.81,  9.94,
       25.56, 19.49, 38.01, 26.41, 11.24, 48.27, 20.29, 13.81, 11.02,
       18.29, 17.59, 20.08, 16.45,  3.07, 20.23, 15.01, 12.02, 17.07,
       26.86, 25.28, 14.73, 10.51, 17.92, 27.2 , 22.76, 17.29, 19.44,
       16.66, 10.07, 32.68, 15.98, 34.83, 13.03, 18.28, 24.71, 21.16,
       28.97, 22.49,  5.75, 16.32, 22.75, 40.17, 27.28, 12.03, 21.01,
       12.46, 11.35, 15.38, 44.3 , 22.42, 20.92, 15.36, 20.49, 25.21,
       18.24, 14.31, 14.  ,  7.25, 38.07, 23.95, 25.71, 17.31, 29.93,
       10.65, 12.43, 24.08, 11.69, 13.42, 14.26, 15.95, 12.48, 29.8 ,
        8.52, 14.52,

In [ ]:
population.mean()

19.78594262295082

In [ ]:
samplesize=150
sample=np.random.choice(population,samplesize)
sample.mean()

20.598533333333332

In [ ]:
sample_mean=[]
for i in range(40):
  sample1=np.random.choice(population,samplesize)
  sample_mean.append(sample1.mean())

In [ ]:
np.mean(sample_mean)

19.852851666666666

In [ ]:
population=df.total_bill.values
population_mean = population.mean()
samplesize=150
sample=np.random.choice(population,samplesize)
sample.mean()
sample_mean=[]
for i in range(40):
  sample1=np.random.choice(population,samplesize)
  sample_mean.append(sample1.mean())
np.mean(sample_mean)
print(f"population mean: {population_mean} and sample mean:", np.mean(sample_mean)  )

population mean: 19.78594262295082 and sample mean: 19.57074666666667


In [ ]:
#tip
population=df.tip.values
population_mean = population.mean()
samplesize=150
sample=np.random.choice(population,samplesize)
sample.mean()
sample_mean=[]
for i in range(40):
  sample1=np.random.choice(population,samplesize)
  sample_mean.append(sample1.mean())
np.mean(sample_mean)
print(f"population mean: {population_mean} and sample mean:", np.mean(sample_mean)  )

population mean: 2.99827868852459 and sample mean: 2.9932183333333335


# 1-Tailed Test

In [ ]:
#total_bill
sample=df.total_bill.sample(frac=0.05)

In [ ]:
t_test,p_value=stats.ttest_1samp(sample,df.total_bill.mean())

In [ ]:
if p_value<0.05:
  print("Null Hypothesis H0 is rejected, Ha is accepted, independent, data not distributed properly")
else:
  print("Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly")

Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly


In [ ]:
for i in range (30):
  sample=df.total_bill.sample(frac=0.05)
  t_test,p_value=stats.ttest_1samp(sample,df.total_bill.mean())
  if p_value<0.05:
    print("Null Hypothesis H0 is rejected, Ha is accepted, independent, data not distributed properly")
  else:
    print("Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly")

Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, 

In [ ]:
#tip
for i in range (30):
  sample=df.tip.sample(frac=0.05)
  t_test,p_value=stats.ttest_1samp(sample,df.tip.mean())
  if p_value<0.05:
    print("Null Hypothesis H0 is rejected, Ha is accepted, independent, data not distributed properly")
  else:
    print("Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly")

Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, Ha is rejected, dependent, data is distributed properly
Null Hypothesis H0 is accepted, 

# Hypothesis testing

In [ ]:
              #2-Tailed Test
#total_bill,	tip 	   - H0 is rejected

                #ANOVA
#total_bill, sex	    - H0 is rejected
#total_bill, smoker   - H0 is accepted
#total_bill, day     - H0 is rejected
#total_bill, time	    - H0 is rejected
#total_bill, size    - H0 is rejected

#tip, sex,	          - H0 is accepted
#tip, smoker          - H0 is accepted
#tip, day            - H0 is accepted
#tip, time	          - H0 is accepted
#tip, size            - H0 is rejected

            #Chi-Square Test
#sex, smoker          - H0 is accepted
#sex, day              - H0 is rejected
#sex, time	          - H0 is rejected
#sex, size           - H0 is accepted

#day, time	        - H0 is rejected
#day, size	         - H0 is rejected

#time, size	         - H0 is rejected

# 2-Tailed Test

In [ ]:
#total_bill,	tip
for i in range(20):
  sample1 = df.total_bill.sample(frac=0.04)
  sample2 = df.tip.sample(frac=0.04)

  t_test, p_value = stats.ttest_ind(sample1, sample2)

  if p_value > 0.5:
    print("H0 is accepted")
  else:
    print('H0 is rejected')

H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected
H0 is rejected


# Chi-Square Test

In [ ]:
data = pd.crosstab(df["sex"], df["smoker"])
data

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [ ]:
observed_values = data.values
observed_values

array([[60, 97],
       [33, 54]])

In [ ]:
result = stats.chi2_contingency(observed_values)

In [ ]:
result

Chi2ContingencyResult(statistic=0.0, pvalue=1.0, dof=1, expected_freq=array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]]))

In [ ]:
#sex, smoker - H0 is accepted

data = pd.crosstab(df["sex"], df["smoker"])
observed_values = data.values
chi2_stat, p_value, _, _= stats.chi2_contingency(observed_values)

if p_value > 0.05:
  print("H0 is accepted")
else:
  print("H0 is rejected")


H0 is accepted


In [ ]:
#sex, day

data = pd.crosstab(df["sex"], df["day"])
observed_values = data.values
chi2_stat, p_value, _, _= stats.chi2_contingency(observed_values)

if p_value > 0.05:
  print("H0 is accepted")
else:
  print("H0 is rejected")

H0 is rejected


In [ ]:
#sex, time

data = pd.crosstab(df["sex"], df["time"])
observed_values = data.values
chi2_stat, p_value, _, _= stats.chi2_contingency(observed_values)

if p_value > 0.05:
  print("H0 is accepted")
else:
  print("H0 is rejected")

H0 is rejected


In [ ]:
#sex, size

data = pd.crosstab(df["sex"], df["size"])
observed_values = data.values
chi2_stat, p_value, _, _= stats.chi2_contingency(observed_values)

if p_value > 0.05:
  print("H0 is accepted")
else:
  print("H0 is rejected")

H0 is accepted


In [ ]:
#day, time

data = pd.crosstab(df["day"], df["time"])
observed_values = data.values
chi2_stat, p_value, _, _= stats.chi2_contingency(observed_values)

if p_value > 0.05:
  print("H0 is accepted")
else:
  print("H0 is rejected")

H0 is rejected


In [ ]:
#day, size

data = pd.crosstab(df["day"], df["size"])
observed_values = data.values
chi2_stat, p_value, _, _= stats.chi2_contingency(observed_values)

if p_value > 0.05:
  print("H0 is accepted")
else:
  print("H0 is rejected")

H0 is rejected


In [ ]:
#time, size

data = pd.crosstab(df["time"], df["size"])
observed_values = data.values
chi2_stat, p_value, _, _= stats.chi2_contingency(observed_values)

if p_value > 0.05:
  print("H0 is accepted")
else:
  print("H0 is rejected")

H0 is rejected


# ANOVA

In [ ]:
#total_bill, sex
group = df['sex'].unique()

In [ ]:
data = {}
for i in group:
  data[i]=df["total_bill"][df["sex"]==i]

In [ ]:
data

{'Female': 0      16.99
 4      24.59
 11     35.26
 14     14.83
 16     10.33
        ...  
 226    10.09
 229    22.12
 238    35.83
 240    27.18
 243    18.78
 Name: total_bill, Length: 87, dtype: float64,
 'Male': 1      10.34
 2      21.01
 3      23.68
 5      25.29
 6       8.77
        ...  
 236    12.60
 237    32.83
 239    29.03
 241    22.67
 242    17.82
 Name: total_bill, Length: 157, dtype: float64}

In [ ]:
f_value, p_value = stats.f_oneway( data['Male'], data['Female'] )
print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")

5.188345638458361 0.023611666846859697
H0 - Null hypothesis is rejected which means no relationship exists


In [ ]:
group = df['smoker'].unique()
group

['No', 'Yes']
Categories (2, object): ['Yes', 'No']

In [ ]:
#total_bill, smoker
group = df['smoker'].unique()
data = {}
for i in group:
  data[i]=df["total_bill"][df["smoker"]==i]

f_value, p_value = stats.f_oneway( data['No'], data['Yes'] )
print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")

1.791411952596261 0.18201032884302323
Ha - Null hypothesis is accepted which means relationship exists


In [ ]:
group = df['day'].unique()
group

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [ ]:
#total_bill, day
group = df['day'].unique()
data = {}
for i in group:
  data[i]=df["total_bill"][df["day"]==i]

f_value, p_value = stats.f_oneway(data['Thur'], data['Fri'], data['Sat'], data['Sun'] )
print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")

2.7674794432863363 0.04245383328952047
H0 - Null hypothesis is rejected which means no relationship exists


In [ ]:
#total_bill, time
group = df['time'].unique()
group

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [ ]:
group = df['time'].unique()
data = {}
for i in group:
  data[i]=df["total_bill"][df["time"]==i]

f_value, p_value = stats.f_oneway(data['Lunch'], data['Dinner'] )
print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")

8.396303207955595 0.00410462140759571
H0 - Null hypothesis is rejected which means no relationship exists


In [ ]:
#total_bill, size
group = df['size'].unique()
group

array([2, 3, 4, 1, 6, 5])

In [ ]:
group = df['size'].unique()
data = {}
for i in group:
  data[i]=df["total_bill"][df["size"]==i]

f_value, p_value = stats.f_oneway(data[1], data[2], data[3], data[4], data[5], data[6] )
print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")

28.09461523749822 2.434919254210166e-22
H0 - Null hypothesis is rejected which means no relationship exists


In [ ]:
#tip, sex,
group = df['sex'].unique()
group

['Female', 'Male']
Categories (2, object): ['Male', 'Female']

In [ ]:
group = df['sex'].unique()
data = {}
for i in group:
  data[i]=df["tip"][df["sex"]==i]

f_value, p_value = stats.f_oneway(data['Male'], data['Female'] )
print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")

1.9261545619320048 0.166456235034572
Ha - Null hypothesis is accepted which means relationship exists


In [ ]:
#tip, smoker
group = df['smoker'].unique()
group

['No', 'Yes']
Categories (2, object): ['Yes', 'No']

In [ ]:
group = df['smoker'].unique()
data = {}
for i in group:
  data[i]=df["tip"][df["smoker"]==i]

f_value, p_value = stats.f_oneway(data['No'], data['Yes'] )
print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")

0.008506013551529044 0.926593152224447
Ha - Null hypothesis is accepted which means relationship exists


In [ ]:
#tip, day
group = df['day'].unique()
group

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [ ]:
group = df['day'].unique()
data = {}
for i in group:
  data[i]=df["tip"][df["day"]==i]

f_value, p_value = stats.f_oneway(data['Thur'], data['Fri'], data['Sat'], data['Sun'] )
print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")

1.6723551980998699 0.1735885553040592
Ha - Null hypothesis is accepted which means relationship exists


In [ ]:
#tip, time
group = df['time'].unique()
group

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [ ]:
group = df['time'].unique()
data = {}
for i in group:
  data[i]=df["tip"][df["time"]==i]

f_value, p_value = stats.f_oneway(data['Lunch'], data['Dinner'] )
print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")

3.633815483631457 0.05780153475171573
Ha - Null hypothesis is accepted which means relationship exists


In [ ]:
#tip, size
group = df['size'].unique()
group

array([2, 3, 4, 1, 6, 5])

In [ ]:
group = df['size'].unique()
data = {}
for i in group:
  data[i]=df["tip"][df["size"]==i]

f_value, p_value = stats.f_oneway(data[1], data[2], data[3], data[4], data[5], data[6] )
print(f_value, p_value)
if p_value<0.05:
  print("H0 - Null hypothesis is rejected which means no relationship exists")
else:
  print("Ha - Null hypothesis is accepted which means relationship exists")

15.746330672727057 2.1694633916208174e-13
H0 - Null hypothesis is rejected which means no relationship exists


# **Data Visualization**



In [ ]:
correlation_matrix = df.corr()
fig = px.imshow(correlation_matrix, color_continuous_scale='Viridis',
                title="Correlation Matrix")
fig.show()

<ipython-input-41-ebcbbf98ef30>:1: FutureWarning:

The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.



In [ ]:
#total_bill,	tip
fig = px.scatter(data_frame=df, x="total_bill", y="tip", color="sex", trendline="ols",
                 title="Scatter Plot")
fig.show()


In [ ]:
#total_bill, day
df = px.data.tips()
fig = px.bar(data_frame=df, x="day", y="total_bill", color="sex", barmode="group",
             title="Clustered Bar Chart")
fig.show()


In [ ]:
#sex, smoker
fig = px.bar(data_frame=df, x="sex", y="smoker", color="sex", barmode="stack",
             title="Stacked Bar Chart")
fig.show()


In [ ]:
#tip, day
fig = px.bar(df, x = 'day',
                 y = 'tip',

                 title = 'Day vs Tip'
                )
fig.show()